model_name: SGNetTrajBbox
dataset: PSI2.0

model_cfg:
        observe_length: 15
        predict_length: 45

        bbox_module:
                input_dim: 4
                embed_dim: 256

        speed_module:
                input_dim: 1
                embed_dim: 128
        

        cvae:
                input_dim: 4
                pred_dim: 4
                latent_dim: 32
                hidden_size: 384
                nu: 0.0
                sigma: 1.5
                latent_dim: 32
                dec_with_z: True
        

        input_dim: 4
        pred_dim: 4
        hidden_size: 384
        latent_dim: 32
        enc_steps: 15
        dec_steps: 45
        dropout: 0.0
        K: 20
                

optimization:
        batch_size: 16
        num_epochs: 50

        optimizer: Adam
        lr: 0.0005
        weight_decay: 0.0

lr_scheduler:
        scheduler: ReduceLROnPlateau
        factor: 0.2
        patience: 5
        min_lr: 0.0000000001 # 1e-10's=
