model_name: SGNetCVAETrajBbox
dataset: PSI2.0

model_cfg:
        observe_length: 15
        predict_length: 45

        bbox_module:
                input_dim: 4
                output_dim: 256

        flow_module:
                input_dim: 2
                output_dim: 320

        cvae:
                input_dim: 4
                pred_dim: 4
                latent_dim: 32
                hidden_size: 512
                nu: 0.0
                sigma: 1.5
                latent_dim: 32
                dec_with_z: True

        input_dim: 4
        pred_dim: 4
        hidden_size: 512
        latent_dim: 32
        enc_steps: 15
        dec_steps: 45
        dropout: 0.0
        K: 1 #20

optimization:
        batch_size: 128
        num_epochs: 25

        optimizer: Adam
        lr: 0.0005
        weight_decay: 0.0

lr_scheduler:
        scheduler: StepLR
        step_size: 5
        gamma: 0.5