model_name: SGNetTrajBbox
dataset: PSI2.0

model_cfg:
        observe_length: 15
        predict_length: 45

        bbox_module:
                input_dim: 4
                output_dim: 128

        flow_module:
                input_dim: 2
                output_dim: 320

        speed_module:
                input_dim: 1
                output_dim: 64

        pred_dim: 4
        hidden_size: 512
        enc_steps: 15
        dec_steps: 45
        dropout: 0.0

optimization:
        batch_size: 128
        num_epochs: 25

        optimizer: Adam
        lr: 0.001
        weight_decay: 0.0

lr_scheduler:
        scheduler: none